Project page responsiveness fix
uci-ieee/ops-webpages-2023-2024 pull request #116
Opened 2024-01-11 08:13 UTC by bcbielecki

The css classes applied to the <img> elements on Project 2 and Project 5 will need to be updated.

<img> should not be wrapped in <p> or <div> without other elements in the parent element.

Project 1 has some unrelated fishy business going on, which causes the content to push past the viewport on mobile devices. Will investigate later...

Closes #85 
Closes #40 
Closes #76

2024-01-11 15:55 UTC, antwonio approved these changes
Looks good to me

2024-01-12 09:02 UTC, dylanvu requested changes

2024-01-12 09:04 UTC, bcbielecki commented on project_1.html
> +<meta charset="utf-8" name="viewport" content="width=device-width, initial-scale=1">
Yes. Yes, it is. Mb.

2024-01-12 09:10 UTC, dylanvu approved these changes
lgtm

2024-01-12 09:10 UTC, merged