Project 2 spec
uci-ieee/ops-webpages-2023-2024 pull request #13
Opened 2023-07-30 03:39 UTC by deonn1

Still need to update the links on the webpage and connect it to the home page.

2023-08-01 21:35 UTC, ieee-uci submitted a review, later dismissed
Suggested changes left on discord -Antonio

2023-10-02 01:13 UTC, bcbielecki submitted a review, later dismissed
Hi guys! Please update the PR with all the Project 2 doc changes from the last month. Let me know when you're done by resolving my change request and requesting another review.

2023-10-02 02:03 UTC, bcbielecki requested changes
Hi guys! Good work on the page. I left a couple of comments, which should be quick to resolve.

This next one may take a bit longer: I noticed that the images don't properly break down when the viewport decreases in width. The text and images overflow (via scrollbar) off the right edge of the viewport.

Instead, we should see the images with any alignment break down into a "center-aligned"-"break text"-style.

This can be accomplished using Bootstrap breakpoints along with bootstrap's CSS classes. You can find more on this here: https://getbootstrap.com/docs/5.1/layout/breakpoints/

Talk to Dylan and Gavin about this. They will be working through a similar issue on their project page.

2023-10-31 10:48 UTC, bcbielecki requested changes
Hi guys! Here are my last couple review comments.

Please also update the ops_header.js file to include the new project 2 link in the "Projects" dropdown

2023-10-31 10:48 UTC, bcbielecki commented on project_2.html
> +				Learn more about 555 Timer’s functionality in the lecture material <span class="text-blue">here [Webpage Link]</span>.
![image](https://github.com/uci-ieee/ops-webpages-2023-2024/assets/45702229/6367b580-cda2-481c-990f-bafbf1023e59)

Please replace this placeholder with a link to the lectures page.

We could rewrite this line to say "Learn more about the 555 Timer's functionality in the Lecture II material here"

2023-10-31 10:48 UTC, bcbielecki commented on project_2.html
> +				href="https://docs.google.com/presentation/d/11AWxHFSlhvF4bWnvbFpBkxV5KOSYh7OgkUuCPrOEb2k/edit?usp=sharing" target="_blank" rel="noopener noreferrer">here</a>.
![image](https://github.com/uci-ieee/ops-webpages-2023-2024/assets/45702229/1c4cf5f8-cbfd-4ea8-b4fb-11c6f054c396)

Now that there's a workshops page, please update the hyperlink to redirect to workshops.html

2023-10-31 10:48 UTC, bcbielecki commented on project_2.html
> +							Schematic B (555 Piano)
![image](https://github.com/uci-ieee/ops-webpages-2023-2024/assets/45702229/6b455fb4-9076-495a-b3f0-fc06a83b4fea)
![image](https://github.com/uci-ieee/ops-webpages-2023-2024/assets/45702229/5f0642ae-40ae-45c1-a089-210254a1bb35)

Please update the Schematic B to be a more legible sizing (consistent with Schematic A)

2023-11-02 05:25 UTC, closed without merging