FAQ page rough draft
uci-ieee/ops-webpages-2023-2024 pull request #49
Opened 2023-09-27 22:41 UTC by daveschoening

First edits on faq page

2023-09-28 22:06 UTC, leavenember commented
What's the plan with the timeline section here?

2023-09-29 04:28 UTC, bcbielecki commented
Hi David! Good work; we're almost done here! Please add the FAQ link to the navbar in the header.js file, and resolve the comments.

2023-09-29 04:33 UTC, bcbielecki requested changes
Hi David! Good work; we're almost done here! Please add the FAQ link to the navbar in the header.js file, and resolve the comments.

2023-09-29 04:33 UTC, bcbielecki commented on faq.html
> +        <!-- Section: Timeline -->
Hi David. It looks like you copied over the timeline from the syllabus page. The elements are hidden from the viewport, but please remove the code anyway. It's extraneous.

2023-10-02 01:26 UTC, closed without merging

2023-10-02 01:26 UTC, bcbielecki commented
Deprecated. Another PR replace this one.